server:
  port: 10000

# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://81.69.6.206:3306/dggmall_pms
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: youis218945

# mybatis-plus配置
mybatis-plus:
  # mapper.xml 扫描
  mapper-locations: classpath*:/mapper/**/*.xml
  # 配置主键自增
  global-config:
    db-config:
      id-type: auto
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

